### ISSUE TITLE
legstar.avro and REDEFINES issue

### ISSUE THREAD

**Issue by spolavar** [legsem/legstar.avro#7]
Hi Fady,

I am testing out legstar libraries for a possible real-time ETL from mainframe to Hadoop. However, my attempts with legstar.avro kinda hit a wall when I encountered the duplicate error caused due to avro union on Cobol REDEFINES clause, which was confirmed [here](https://github.com/legsem/legstar.avro/issues/5). My question is follow-up to this.

The nature of data that I'm trying to convert is full of these cases, where the REDEFINES clause is used to save memory and sometimes reuses a field declaration on exact same types. **Does legstar.avro or any other legstar libraries support any kind of workaround for these cases? so if manipulation is needed it can be handled within the library!?**

I also tried legstar core2 hoping to avoid any kind of manipulation to the COBOL files prior to conversion. So far I've had some success with legstar-base-generator, but here I'm facing different issues.

Ex1: When the Copybook is manipulated to overcome the errors due to REDEFINES clause, the conversion happens but only partially.

Here is what I see:
My test follows the example provided

> "legstar.samples.custdat.CustdatSample.java"

but with my own sample of copybook and binary data files. I see that that only ~7kb of the total 160kb of the binary stream is converted. As a result, only 1 record is converted instead of 10 from my mainframe data. My question is, How to I ensure all 160kb are processed. I don't see any error hence I don't have a clear understanding of what's causing the issue, but I believe the visitor object for some reason is unable to build the byte stream using my "CustomCopyBook.java". Unfortunately, I cannot share my test results due to policy reasons.

Ex2: when The Copybook is not manipulated then I run into following error:

`com.legstar.base.visitor.CobolChoiceStrategyException: Unable to select an alternative for choice pricingAmount1CpTw1Choice, path:TWR-SPLIT-RECORD-TYPE-1/TWR-SPLIT-DATA-TYPE-1/CHARGE-LINE-TABLE-TW1[0]/CHARGE-LINE-TW1/PRICING-DATA-TW1`

> the corresponding copybook definition for that field has REDEFINES on cobol compressed type.

My goal is to be able to test for one complete conversion and quantify how much of pre-processing is necessary for it. I want to seek your recommendation(s) on ways of handling the REDEFINES declarations, and whether I am missing anything in my approach to test legstar APIs,

Thanks

**Comment by fmoussallam** [comment]
Concerning the REDEFINES where alternatives are primitive types, this should be addressed in com.legstar.avro.translator.Xsd2AvroTranslator. In such cases, we should wrap the primitive types in avro named records. This way, avro will no longer complain that the same type is used several times in a union.

On your second point, as to why processing stops after partial processing, the CustdatSample processes a single record of data and then stops. If you want to process more than one record, you have to implement logic similar to ZosVarDatumReader#readRecord to iterate over records. 

Finally, concerning CobolChoiceStrategyException, this is raised when the choice strategy which is invoked on REDEFINES to identify the proper alternative fails. There is a default strategy (com.legstar.base.visitor.DefaultFromCobolChoiceStrategy) that is used unless you provide your own. The default strategy parses the input using each of the alternatives in turn and picks the first one that successfully parses the input. If none parses the input, you get that exception. Its usually a sign that something is off between the data and the generated code.

Hope this helps.

**Comment by spolavar** [comment]
Thank you for your suggestions! While I am trying out your workarounds, I was wondering about the REDEFINES on BINARY and COMP-3 types? Can they also be handled similarly using avro named record wrappers? Do you have any examples for these cases?

**Comment by glangho** [comment]
Has anyone figured out how to do this?  I'm unsure how com.legstar.avro.translator.Xsd2AvroTranslator is supposed to address this issue.  I'm still getting failures like:

    Exception in thread "main" org.apache.avro.AvroRuntimeException: Duplicate in union:int

for things like this:

    10  DATE                                          COMP PIC S9(8).
    10  OTHER-DATE REDEFINES DATE COMP PIC S9(8).

Is there some config option that needs to be explicitly set?
